# SETTINGS FOR ANIMAL PLAGUE
Plagues:
  OverpopulationSyndrome:
    enabled: true
    infection:
      check-radius: 10
      max-animals: 5
      infection-time: 300L
      spread-chance: 0.3
      stages:
        infection-to-effect: 600 # ticks (30 Sekunden)
        effect-to-death: 1200    # ticks (60 Sekunden)
    entites:
      - "CHICKEN"
      - "COW"
