name: AnimalPlague
version: '1.0-SNAPSHOT'
main: io.zetprogram.animalPlague.AnimalPlague
api-version: '1.20'
commands:
  animalplague:
    description: "Main command for AnimalPlague plugin"
    usage: "/animalplague <reload|infostick>"
