name: AnimalPlague
version: '1.0-SNAPSHOT'
main: io.zetprogram.animalPlague.AnimalPlague
api-version: '1.20'
commands:
  animalplague:
    description: "Reload the plugin configuration"
    usage: "/animalplague reload"